version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
#  db:
#    image: mysql
#    command:
#      - "--default-authentication-plugin=mysql_native_password"
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpassword
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "9000:8080"